apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-rag
  labels:
    app: eks-rag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-rag
  template:
    metadata:
      labels:
        app: eks-rag
    spec:
      serviceAccountName: eks-rag-sa
      containers:
      - name: eks-rag
        image: ${ECR_REPO}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: VLLM_HOST
          value: "vllm-llama3-inf2-serve-svc.vllm.svc.cluster.local"
        - name: VLLM_PORT
          value: "8000"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30  
          timeoutSeconds: 10      
          periodSeconds: 15       
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60  
          timeoutSeconds: 10      
          periodSeconds: 20       
